"""Contract-pinned document, locator, result, and diagnostic shapes.

Field pins are frozen at plan Step 1 (plan.md §5). Identifier composition
(``doc_id`` and ``content_hash``) is defined here once (plan.md §6 Identifiers),
generated by the indexer, and consumed by the storage and search layers.

Nothing in this module reads files, touches the database, or performs
exclusion; it is pure data plus identifier helpers.
"""

from __future__ import annotations

import enum
import hashlib
import os
from dataclasses import dataclass

__all__ = [
    "ArtifactType",
    "Diagnostic",
    "IndexedDocument",
    "Locator",
    "SearchResult",
    "Severity",
    "content_hash",
    "make_doc_id",
    "normalize_source_path",
]


class ArtifactType(enum.Enum):
    """Supported artifact families (plan.md §5 IndexedDocument.artifact_type)."""

    MARKDOWN = "markdown"
    JSON = "json"
    JSONL = "jsonl"
    PLAN = "plan"
    HANDOFF = "handoff"
    DECISION = "decision"
    INCIDENT = "incident"
    MEMORY = "memory"


class Severity(enum.Enum):
    """Diagnostic severity (plan.md §5 Diagnostic.severity)."""

    WARN = "warn"
    ERROR = "error"


@dataclass(frozen=True, slots=True)
class Locator:
    """An openable pointer back into a source artifact (plan.md §5 Locator).

    ``source_path`` is a root-relative POSIX path. ``line_start``/``line_end``
    give an optional line span; ``record_key`` names an optional record within a
    multi-document file (JSON/JSONL). :meth:`rendered` returns the openable
    ``path:line`` form.
    """

    source_path: str
    line_start: int | None = None
    line_end: int | None = None
    record_key: str | None = None

    def rendered(self) -> str:
        """Render as an openable ``path:line`` (or ``path::record_key``) string."""
        if self.line_start is not None:
            if self.line_end is not None and self.line_end != self.line_start:
                return f"{self.source_path}:{self.line_start}-{self.line_end}"
            return f"{self.source_path}:{self.line_start}"
        if self.record_key is not None:
            return f"{self.source_path}::{self.record_key}"
        return self.source_path


@dataclass(frozen=True, slots=True)
class IndexedDocument:
    """A single indexable document (plan.md §5 IndexedDocument).

    ``doc_id`` is the primary key (see :func:`make_doc_id`); ``content_hash`` is
    the SHA-256 hex of the raw file bytes (see :func:`content_hash`).
    ``record_locator`` is populated only for multi-document files.
    """

    doc_id: str
    source_path: str
    artifact_type: ArtifactType
    project: str
    timestamp: str
    content_hash: str
    body: str
    record_locator: str | None = None


@dataclass(frozen=True, slots=True)
class SearchResult:
    """A ranked search hit (plan.md §5 SearchResult)."""

    doc_id: str
    type: ArtifactType
    timestamp: str
    excerpt: str
    locator: Locator
    rank: float


@dataclass(frozen=True, slots=True)
class Diagnostic:
    """A skipped-or-failed file report (plan.md §5 Diagnostic).

    Safety contract: ``message`` MUST NEVER contain excluded or matched content.
    Exclusion and adapter code constructs ``message`` from stable ``code``/pattern
    identifiers and the ``source_path`` only — never from file bytes or a matched
    secret span.
    """

    source_path: str
    adapter: str
    severity: Severity
    code: str
    message: str


def normalize_source_path(source_path: str | os.PathLike[str]) -> str:
    """Normalize a (root-relative) path to POSIX separators.

    Deterministic across platforms: backslashes become forward slashes so a
    document indexed on Windows and one indexed on Linux share a ``doc_id``.
    """
    return str(source_path).replace("\\", "/")


def make_doc_id(source_path: str | os.PathLike[str], record_locator: str | None = None) -> str:
    """Compose a ``doc_id`` (plan.md §6 Identifiers).

    ``doc_id`` is the POSIX-normalized root-relative source path, plus
    ``::<record-locator>`` for multi-document files
    (e.g. ``runs/telemetry.jsonl::L42``).
    """
    base = normalize_source_path(source_path)
    if record_locator:
        return f"{base}::{record_locator}"
    return base


def content_hash(data: bytes) -> str:
    """SHA-256 hex over raw file bytes (plan.md §6 Identifiers).

    File-level; drives incremental refresh reconciliation.
    """
    return hashlib.sha256(data).hexdigest()
